### ISSUE TITLE
Panic when closing daemon

### ISSUE THREAD

**Issue by victorb** [filecoin-project/go-filecoin#1155]
Happened when stopping the daemon, didn't force stop it, just a normal ctrl+c

```
^CGot interrupt, shutting down...
16:12:29.361 WARNI   api/impl: error decoding event: io: read/write on closed pipe log.go:108
16:12:29.361 WARNI   commands: StreamTo closed, re-starting... readfrom tcp4 10.99.76.237:37030->34.230.8.232:19000: io: read/write on closed pipe log.go:65
failed to shut down api server: context deadline exceeded
16:12:34.473 ERROR       node: MessageSub.Next(): context canceled blocks.go:51
16:12:34.473 ERROR       node: BlockSub.Next(): context canceled blocks.go:51
16:12:34.473 WARNI     swarm2: swarm listener accept error: accept tcp 0.0.0.0:6000: use of closed network connection swarm_listen.go:77
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9985e2]

goroutine 233587 [running]:
gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger/skl.(*Skiplist).IncrRef(...)
        /go/src/gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger/skl/skl.go:86
gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger.(*DB).getMemTables(0xc4204f8e00, 0x0, 0x0, 0x0, 0x0)
        /go/src/gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger/db.go:472 +0xd2
gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger.(*DB).get(0xc4204f8e00, 0xc436b5c780, 0x4a, 0x4a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger/db.go:496 +0x66
gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger.(*Txn).Get(0xc43b1377a0, 0xc436b5c730, 0x42, 0x50, 0x42, 0x50, 0xc436b5c6e0)
        /go/src/gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger/transaction.go:388 +0x109
gx/ipfs/QmciWFTxK1t1PNyPdoTsv8wtj3DWim2qRFjaUEcFWCnV8D/go-ds-badger.(*Datastore).Get(0xc42018e100, 0xc436b5c6e0, 0x42, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/gx/ipfs/QmciWFTxK1t1PNyPdoTsv8wtj3DWim2qRFjaUEcFWCnV8D/go-ds-badger/datastore.go:88 +0xd6
gx/ipfs/QmVG5gxteQNEMhrS8prJSmU2C9rebtFuTd3SYZ5kE3YZ5k/go-datastore/keytransform.(*ktds).Get(0xc42000c9e0, 0xc435a37180, 0x3b, 0xc435a37100, 0x24, 0x36, 0xc435a37180, 0x3b)
        /go/src/gx/ipfs/QmVG5gxteQNEMhrS8prJSmU2C9rebtFuTd3SYZ5kE3YZ5k/go-datastore/keytransform/keytransform.go:42 +0x76
gx/ipfs/QmcmpX42gtDv1fz24kau4wjS9hfwWj5VexWBKgGnWzsyag/go-ipfs-blockstore.(*blockstore).Get(0xc42000ca00, 0xc43610cc60, 0x0, 0xc43340ce10, 0x1, 0x1)
        /go/src/gx/ipfs/QmcmpX42gtDv1fz24kau4wjS9hfwWj5VexWBKgGnWzsyag/go-ipfs-blockstore/blockstore.go:123 +0x62
gx/ipfs/QmTfTKeBhTLjSjxXQsjkF2b1DfZmYEMnknGE2y2gX57C6v/go-blockservice.getBlock(0xed2d20, 0xc439c706c0, 0xc43610cc60, 0xed6fe0, 0xc42000ca00, 0x7f17b47bc2f0, 0xc42018e600, 0x0, 0xc4359bcea0, 0xc439c706c0, ...)
        /go/src/gx/ipfs/QmTfTKeBhTLjSjxXQsjkF2b1DfZmYEMnknGE2y2gX57C6v/go-blockservice/blockservice.go:216 +0x6c
gx/ipfs/QmTfTKeBhTLjSjxXQsjkF2b1DfZmYEMnknGE2y2gX57C6v/go-blockservice.(*blockService).GetBlock(0xc420192bd0, 0xed2d20, 0xc439c706c0, 0xc43610cc60, 0xc439c706c0, 0xc43340ce00, 0x30, 0xc63300)
        /go/src/gx/ipfs/QmTfTKeBhTLjSjxXQsjkF2b1DfZmYEMnknGE2y2gX57C6v/go-blockservice/blockservice.go:207 +0xfd
gx/ipfs/QmQZadYTDF4ud9DdK85PH2vReJRzUM9YfVW4ReB1q2m51p/go-hamt-ipld.(*CborIpldStore).Get(0xc4201dc820, 0xed2d20, 0xc439c706c0, 0xc43610cc60, 0xcb9d20, 0xc4352e9e30, 0x0, 0x0)
        /go/src/gx/ipfs/QmQZadYTDF4ud9DdK85PH2vReJRzUM9YfVW4ReB1q2m51p/go-hamt-ipld/ipld.go:81 +0xb9
gx/ipfs/QmQZadYTDF4ud9DdK85PH2vReJRzUM9YfVW4ReB1q2m51p/go-hamt-ipld.LoadNode(0xed2d60, 0xc4352e86c0, 0xc4201dc820, 0xc43610cc60, 0x38, 0xc431befad0, 0x0)
        /go/src/gx/ipfs/QmQZadYTDF4ud9DdK85PH2vReJRzUM9YfVW4ReB1q2m51p/go-hamt-ipld/hamt.go:110 +0x78
github.com/filecoin-project/go-filecoin/state.LoadStateTree(0xed2d60, 0xc4352e86c0, 0xc4201dc820, 0xc43610cc60, 0xc4204f0db0, 0xc431befad0, 0x0, 0x0, 0xc435a370c0)
        /go/src/github.com/filecoin-project/go-filecoin/state/tree.go:47 +0x4d
github.com/filecoin-project/go-filecoin/api/impl.(*nodeMining).Once.func1(0xed2d60, 0xc4352e86c0, 0xc435a370c0, 0x38, 0x42cfd9, 0xc43408a440, 0xc439c61c78, 0x18)
        /go/src/github.com/filecoin-project/go-filecoin/api/impl/mining.go:36 +0xda
github.com/filecoin-project/go-filecoin/api/impl.(*nodeMining).Once.func2(0xed2d60, 0xc4352e86c0, 0xc440481a70, 0xed2d60, 0xc4352e86c0, 0xed2d60, 0xc4352e86c0)
        /go/src/github.com/filecoin-project/go-filecoin/api/impl/mining.go:39 +0x69
github.com/filecoin-project/go-filecoin/mining.(*DefaultWorker).Mine(0xc43ee54e00, 0xed2d60, 0xc4352e86c0, 0xc440481a70, 0x862, 0xc4350363c0)
        /go/src/github.com/filecoin-project/go-filecoin/mining/worker.go:128 +0x28d
github.com/filecoin-project/go-filecoin/mining.(*timingScheduler).Start.func1(0xc438001060, 0xed2ca0, 0xc43ea5af00, 0xc43500ce40, 0xc4350363c0)
        /go/src/github.com/filecoin-project/go-filecoin/mining/scheduler.go:112 +0xcc
created by github.com/filecoin-project/go-filecoin/mining.(*timingScheduler).Start
        /go/src/github.com/filecoin-project/go-filecoin/mining/scheduler.go:91 +0x117
```

**Comment by anorth** [comment]
Closing for #2052
