### ISSUE TITLE
[bug] crash after run about 10 minitus

### ISSUE THREAD

**Issue by haoglehaogle** [filecoin-project/go-filecoin#2021]
**Describe the bug**
  Environment:
  - Software :  ubuntu 18.04
  - Hardware:  intel j1900 4 cores; memory: 4G
   go-filecoin will exit after running about 10 minitues, detail information is the below. I also compile it and run on Mac OS is well still. (memory 8G, double cores, i5)
 - Version 
    Compile from master branch
**Additional context**
```
15:46:25.135  INFO    autonat: Discovered AutoNAT peer QmczxH1SNMmZ8LDct1E9yeP9KxFwVe2P89JRh2JdjfnNyj notify.go:33
15:46:30.832  INFO    autonat: Discovered AutoNAT peer QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV notify.go:33
15:46:34.410 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*QvwuiV>: stream reset hello.go:150
15:46:35.172 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*nWqBX6>: stream reset hello.go:150
15:46:52.297  INFO    autonat: Discovered AutoNAT peer QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV notify.go:33
15:47:01.322  INFO    autonat: Discovered AutoNAT peer QmczxH1SNMmZ8LDct1E9yeP9KxFwVe2P89JRh2JdjfnNyj notify.go:33
15:47:04.895  INFO    autonat: Discovered AutoNAT peer QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV notify.go:33
15:47:13.022  INFO    autonat: Discovered AutoNAT peer QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV notify.go:33
15:47:14.216  INFO    autonat: Discovered AutoNAT peer QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg notify.go:33
15:48:23.296 WARNI net/identi: error reading identify message:  short buffer id.go:135
15:48:52.439 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*ENtgKT>: stream reset hello.go:150
15:48:52.439 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*ENtgKT>: stream reset hello.go:150
15:48:55.465 WARNI net/identi: error reading identify message:  short buffer id.go:135
15:49:04.043 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*2hY17n>: stream reset hello.go:150
15:49:31.643 WARNI net/identi: error reading identify message:  short buffer id.go:135
15:49:35.495 WARNI net/identi: error reading identify message:  short buffer id.go:135
15:50:20.191 WARNI net/identi: error reading identify message:  short buffer id.go:135
15:50:24.580 WARNI net/identi: error reading identify message:  short buffer id.go:135
15:52:44.827 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*U2BS8k>: stream reset hello.go:150
15:52:44.827 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*U2BS8k>: stream reset hello.go:150
15:52:45.808 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*s7agiT>: stream reset hello.go:150
15:52:45.809 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*s7agiT>: stream reset hello.go:150
15:52:47.331 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*YUK9i2>: stream reset hello.go:150
15:52:47.331 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*YUK9i2>: stream reset hello.go:150
15:54:30.346 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*KTUVB4>: stream reset hello.go:150
15:54:31.777 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*4dVZ33>: stream reset hello.go:150
15:54:31.777 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*4dVZ33>: stream reset hello.go:150
15:54:42.867 WARNI net/identi: error reading identify message:  short buffer id.go:135
15:54:55.795 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*RPUgtu>: stream reset hello.go:150
memory allocation of 544230432 bytes failedSIGABRT: abort
PC=0x7faa6699ae97 m=6 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7faa6699ae97
stack: frame={sp:0x7faa622430e0, fp:0x0} stack=[0x7faa61a49088,0x7faa62248c88)
00007faa62242fe0:  00007faa66f6db90  00007fa820d1fd28 
00007faa62242ff0:  0000000000201000  0000000000000000 
00007faa62243000:  00007faa00000003  00007faa675a32b7 
00007faa62243010:  00007faa62243110  0000000000000001 
00007faa62243020:  0000000000000001  00007fa7a7ae3cb0 
00007faa62243030:  00007faa677afce0  00007faa66f762cc 
00007faa62243040:  0000000000000001  0000000000000009 
00007faa62243050:  0000000000000009  00007faa66f76270 
00007faa62243060:  00007faa66f790e0  0000000000eb6da5 
00007faa62243070:  00007fa820d1f700  0000000000000000 
00007faa62243080:  0000000000000000  0000000000000009 
00007faa62243090:  00007fa82071c700  00007faa62243288 
00007faa622430a0:  00007faa622431e0  00000000014de1a8 
00007faa622430b0:  0000000000000009  00007faa622431a7 
00007faa622430c0:  0000000000000040  0000000000eb6feb 
00007faa622430d0:  00007faa622431d0  00007faa62243230 
00007faa622430e0: <0000000000000000  0000000000000017 
00007faa622430f0:  0000000000000017  00007faa66f762cc 
00007faa62243100:  0000000000000000  000000000000000d 
00007faa62243110:  000000000000000d  00007faa66f76270 
00007faa62243120:  00007faa66f790e0  0000000000eb6da5 
00007faa62243130:  00007faa62243138  00000000014e2250 
00007faa62243140:  0000000000000000  000000000000000d 
00007faa62243150:  0000000000000020  00007faa62243288 
00007faa62243160:  fffffffe7fffffff  ffffffffffffffff 
00007faa62243170:  ffffffffffffffff  ffffffffffffffff 
00007faa62243180:  ffffffffffffffff  ffffffffffffffff 
00007faa62243190:  ffffffffffffffff  ffffffffffffffff 
00007faa622431a0:  ffffffffffffffff  ffffffffffffffff 
00007faa622431b0:  ffffffffffffffff  ffffffffffffffff 
00007faa622431c0:  ffffffffffffffff  ffffffffffffffff 
00007faa622431d0:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7faa6699ae97
stack: frame={sp:0x7faa622430e0, fp:0x0} stack=[0x7faa61a49088,0x7faa62248c88)
```

**Comment by travisperson** [comment]
Something that may help get around this limitation is to check if `/tmp` is a `tmpfs` (backed by ram). The PoR params are stored there by default which might be taking up a significant portion of your memory. You can work around this by either setting the env var `FILECOIN_PARAMETER_CACHE` (and moving over the `v9-zigzag-proof-of-replication-*` files), or symlinking `/tmp/filecoin-proof-parameters/` out of `/tmp` so that it's backed by disk storage.

**Comment by mishmosh** [comment]
@haoglehaogle did you have a chance to try the env variable or symlinking workarounds suggested above?

Removing P0 label (reserved for devnet-crashing panics, etc.).

**Comment by yangjian102621** [comment]
I ran into the the same problem, then i set the env var `FIL_USE_SMALL_SECTORS=true ` and the problem is disappeared.
Just run this script:

`env FIL_USE_SMALL_SECTORS=true go-filecoin daemon` 

The cpu usage dropped from 400% to 100%, and it did not crash again.
