### ISSUE TITLE
[bug] can't finish the deal flow

### ISSUE THREAD

**Issue by life-i** [filecoin-project/go-filecoin#2038]
### Description
**
i'm running two actors 
after the second actor deal with the first actor
the deal status change to accepted
but the first actor and it's mining  is shutdown
go-filecoin version
`commit: e83f35d3db3a66346a7ea027ca76292e5c154601`

the console output
**
```
goroutine 436602 [IO wait]:
internal/poll.runtime_pollWait(0x7f0a7287d470, 0x72, 0xc006b60ac0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc02016bd98, 0x72, 0xffffffffffffff00, 0x150a320, 0x1f99338)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc02016bd98, 0xc0269d0100, 0x4, 0x4)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc02016bd80, 0xc0269d01b0, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc02016bd80, 0xc0269d01b0, 0x4, 0x4, 0xc0288f1b80, 0xc, 0x40)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc020a1dd40, 0xc0269d01b0, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x68
io.ReadAtLeast(0x7f0a64b4bfe8, 0xc01c9d4a20, 0xc0269d01b0, 0x4, 0x4, 0x4, 0xc00013c090, 0xc02390b580, 0x4fc83b)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0x7f0a64b4bfe8, 0xc01c9d4a20, 0xc0269d01b0, 0x4, 0x4, 0xc021bd2f00, 0xaab98a, 0xc00013c090)
	/usr/local/go/src/io/io.go:329 +0x58
gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio.ReadLen(0x7f0a64b4bfe8, 0xc01c9d4a20, 0xc0269d01b0, 0x4, 0x4, 0xc021bd2f00, 0xc006b60d68, 0xc006b60d48)
	/go/src/gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio/num.go:27 +0x74
gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio.(*reader).nextMsgLen(0xc01c5a0730, 0x150d080, 0xc0269d01b8, 0xc006b60d78)
	/go/src/gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio/msgio.go:159 +0x78
gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio.(*reader).NextMsgLen(0xc01c5a0730, 0x0, 0x0, 0x0)
	/go/src/gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio/msgio.go:154 +0x84
gx/ipfs/QmQoDgEDBPJ6RfKDgdoMpPwoK4WEZHUosHoUs6YVDGoen3/go-libp2p-secio.(*etmReader).Read(0xc0000b7ae0, 0xc02750ad80, 0xc, 0xc, 0x0, 0x0, 0x0)
	/go/src/gx/ipfs/QmQoDgEDBPJ6RfKDgdoMpPwoK4WEZHUosHoUs6YVDGoen3/go-libp2p-secio/rw.go:163 +0xcf
io.ReadAtLeast(0x7f0a64c0c3d0, 0xc00688b440, 0xc02750ad80, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0x7f0a64c0c3d0, 0xc00688b440, 0xc02750ad80, 0xc, 0xc, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:329 +0x58
gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.(*Session).recvLoop(0xc006366fc0, 0x0, 0x0)
	/go/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/session.go:535 +0xec
gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.(*Session).recv(0xc006366fc0)
	/go/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/session.go:514 +0x2b
created by gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.newSession
	/go/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/session.go:128 +0x387

goroutine 403905 [select, 1 minutes]:
gx/ipfs/QmYoGLuLwTUv1SYBmsw1EVNC9MyLVUxwxzXYtKgAGHyEfw/go-bitswap/messagequeue.(*MessageQueue).runQueue(0xc02d25c930, 0x15115a0, 0xc0001e8d80)
	/go/src/gx/ipfs/QmYoGLuLwTUv1SYBmsw1EVNC9MyLVUxwxzXYtKgAGHyEfw/go-bitswap/messagequeue/messagequeue.go:103 +0x127
created by gx/ipfs/QmYoGLuLwTUv1SYBmsw1EVNC9MyLVUxwxzXYtKgAGHyEfw/go-bitswap/messagequeue.(*MessageQueue).Startup
	/go/src/gx/ipfs/QmYoGLuLwTUv1SYBmsw1EVNC9MyLVUxwxzXYtKgAGHyEfw/go-bitswap/messagequeue/messagequeue.go:92 +0x202

goroutine 439636 [select]:
gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.(*Stream).Read(0xc01edb45a0, 0xc01b20b000, 0x1, 0x1000, 0x0, 0x0, 0x0)
	/go/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/stream.go:134 +0x24a
gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm.(*Stream).Read(0xc017c259a0, 0xc01b20b000, 0x1, 0x1000, 0xc028863880, 0x4fc60b, 0xc0246f05d0)
	/go/src/gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm/swarm_stream.go:64 +0x6c
gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream.(*lazyClientConn).Read(0xc0246f05b0, 0xc01b20b000, 0x1, 0x1000, 0x4e, 0x4e, 0x0)
	/go/src/gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream/lazyClient.go:76 +0xbd
gx/ipfs/QmYxivS34F2M2n44WQQnRHGAKS8aoRUxwGpi9wk4Cdn4Jf/go-libp2p/p2p/host/basic.(*streamWrapper).Read(0xc01902e2e0, 0xc01b20b000, 0x1, 0x1000, 0x4e, 0xc0288638c8, 0xc028863948)
	/go/src/gx/ipfs/QmYxivS34F2M2n44WQQnRHGAKS8aoRUxwGpi9wk4Cdn4Jf/go-libp2p/p2p/host/basic/basic_host.go:536 +0x52
gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit.(*delimitedReader).ReadByte(0xc01a273d40, 0x4e, 0x4e, 0x0)
	/go/src/gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit/util.go:72 +0x59
encoding/binary.ReadUvarint(0x15086e0, 0xc01a273d40, 0x4e, 0x0, 0x0)
	/usr/local/go/src/encoding/binary/varint.go:110 +0x7b
gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit.(*delimitedReader).ReadMsg(0xc01a273d40, 0x150f1e0, 0xc019b8f1c0, 0x0, 0x0)
	/go/src/gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit/util.go:77 +0x3b
gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit.(*Relay).DialPeer(0xc0000c8620, 0x1511620, 0xc0242e4ae0, 0xc01ceba1b0, 0x22, 0xc01b58a2e0, 0x1, 0x1, 0xc01be767e0, 0x22, ...)
	/go/src/gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit/relay.go:174 +0x5c0
gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit.(*Relay).Dial(0xc0000c8620, 0x1511620, 0xc0242e4ae0, 0x15156c0, 0xc01b574b20, 0xc01be767e0, 0x22, 0x2, 0x2, 0x0)
	/go/src/gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit/dial.go:55 +0x566
gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit.(*RelayTransport).Dial(0xc0000c8620, 0x1511620, 0xc0242e4ae0, 0x15156c0, 0xc01b574b20, 0xc01be767e0, 0x22, 0x10, 0xc01b58a290, 0x3, ...)
	/go/src/gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit/dial.go:15 +0x7d
gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm.(*Swarm).dialAddr(0xc000178000, 0x1511620, 0xc0242e4ae0, 0xc01be767e0, 0x22, 0x15156c0, 0xc01b574b20, 0x0, 0xc01cb8c3f0, 0xc0242e4ae0, ...)
	/go/src/gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm/swarm_dial.go:420 +0x241
gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm.(*Swarm).dialAddr-fm(0x1511620, 0xc0242e4ae0, 0xc01be767e0, 0x22, 0x15156c0, 0xc01b574b20, 0x0, 0x0, 0x1d00, 0x74)
	/go/src/gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm/swarm.go:104 +0x73
gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm.(*dialLimiter).executeDial(0xc0062bed70, 0xc0260eb240)
	/go/src/gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm/limiter.go:184 +0x145
created by gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm.(*dialLimiter).addCheckFdLimit
	/go/src/gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm/limiter.go:139 +0x139

goroutine 439480 [select]:
gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.(*Stream).Read(0xc0062306c0, 0xc021267000, 0x1, 0x1000, 0x0, 0x0, 0x0)
	/go/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/stream.go:134 +0x24a
gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm.(*Stream).Read(0xc006bd5ef0, 0xc021267000, 0x1, 0x1000, 0xc018969880, 0x4fc60b, 0xc0269f37c0)
	/go/src/gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm/swarm_stream.go:64 +0x6c
gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream.(*lazyClientConn).Read(0xc0269f37a0, 0xc021267000, 0x1, 0x1000, 0x4e, 0x4e, 0x0)
	/go/src/gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream/lazyClient.go:76 +0xbd
gx/ipfs/QmYxivS34F2M2n44WQQnRHGAKS8aoRUxwGpi9wk4Cdn4Jf/go-libp2p/p2p/host/basic.(*streamWrapper).Read(0xc019488260, 0xc021267000, 0x1, 0x1000, 0x4e, 0xc0189698c8, 0xc018969948)
	/go/src/gx/ipfs/QmYxivS34F2M2n44WQQnRHGAKS8aoRUxwGpi9wk4Cdn4Jf/go-libp2p/p2p/host/basic/basic_host.go:536 +0x52
gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit.(*delimitedReader).ReadByte(0xc01a85bec0, 0x4e, 0x4e, 0x0)
	/go/src/gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit/util.go:72 +0x59
encoding/binary.ReadUvarint(0x15086e0, 0xc01a85bec0, 0x4e, 0x0, 0x0)
	/usr/local/go/src/encoding/binary/varint.go:110 +0x7b
gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit.(*delimitedReader).ReadMsg(0xc01a85bec0, 0x150f1e0, 0xc019083680, 0x0, 0x0)
	/go/src/gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit/util.go:77 +0x3b
gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit.(*Relay).DialPeer(0xc0000c8620, 0x1511620, 0xc01c621da0, 0xc01c81b5f0, 0x22, 0xc01b81da80, 0x1, 0x1, 0xc0180872f0, 0x22, ...)
	/go/src/gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit/relay.go:174 +0x5c0
gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit.(*Relay).Dial(0xc0000c8620, 0x1511620, 0xc01c621da0, 0x15156c0, 0xc019c6fe80, 0xc0180872f0, 0x22, 0x2, 0x2, 0x0)
	/go/src/gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit/dial.go:55 +0x566
gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit.(*RelayTransport).Dial(0xc0000c8620, 0x1511620, 0xc01c621da0, 0x15156c0, 0xc019c6fe80, 0xc0180872f0, 0x22, 0x10, 0xc01b81da20, 0x3, ...)
	/go/src/gx/ipfs/QmWuMW6UKZMJo9bFFDwnjg8tW3AtKisMHHrXEutQdmJ19N/go-libp2p-circuit/dial.go:15 +0x7d
gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm.(*Swarm).dialAddr(0xc000178000, 0x1511620, 0xc01c621da0, 0xc0180872f0, 0x22, 0x15156c0, 0xc019c6fe80, 0x0, 0xc020ec0870, 0xc01c621da0, ...)
	/go/src/gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm/swarm_dial.go:420 +0x241
gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm.(*Swarm).dialAddr-fm(0x1511620, 0xc01c621da0, 0xc0180872f0, 0x22, 0x15156c0, 0xc019c6fe80, 0x0, 0x0, 0x1d40, 0x75)
	/go/src/gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm/swarm.go:104 +0x73
gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm.(*dialLimiter).executeDial(0xc0062bed70, 0xc020f8c180)
	/go/src/gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm/limiter.go:184 +0x145
created by gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm.(*dialLimiter).addCheckFdLimit
	/go/src/gx/ipfs/QmegQFxhr1J6yZ1vDQuDmJi5jntmj6BL96S11HVtXNCaHb/go-libp2p-swarm/limiter.go:139 +0x139

rax    0x0
rbx    0x400000
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x17344
rsi    0x17346
rbp    0x7f0a6ebfd890
rsp    0x7f0a6ebfd658
r8     0x0
r9     0x9
r10    0x8
r11    0x206
r12    0x8
r13    0x32000000
r14    0x206f02
r15    0x1
rip    0x7f0a7194b2a7
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```

### Acceptance criteria
none
### Risks + pitfalls
none
### Protocol Changes
none
### Where to begin
the second node run  go-filecoin client propose-storage-deal

**Comment by life-i** [comment]
![image](https://user-images.githubusercontent.com/15134789/53085570-236b7480-353e-11e9-8502-96ca358cb9f6.png)
