### ISSUE TITLE
flaky `TestRetrievalProtocolPieceNotFound` test

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2342]
### Description

`TestRetrievalProtocolPieceNotFound` [failed recently](https://circleci.com/gh/filecoin-project/go-filecoin/12841) with an `index out of range` error:

```
panic: runtime error: index out of range

goroutine 473 [running]:
github.com/filecoin-project/go-filecoin/chain.GetRecentAncestors(0x16424a0, 0xc000dd4180, 0xc0006daf30, 0x164c560, 0xc0001535e0, 0xc000dd00c8, 0xc000010340, 0x3, 0x1, 0xc0007dccf8, ...)
	/go/src/github.com/filecoin-project/go-filecoin/chain/get_ancestors.go:59 +0x603
github.com/filecoin-project/go-filecoin/node.(*Node).StartMining.func4(0x16424a0, 0xc000dd4180, 0xc0006daf30, 0xc000dd00c8, 0x0, 0x0, 0xc0008975a0, 0xc000039d00, 0x15)
	/go/src/github.com/filecoin-project/go-filecoin/node/node.go:802 +0x81
github.com/filecoin-project/go-filecoin/mining.(*DefaultWorker).Generate(0xc000c56540, 0x16424a0, 0xc000dd4180, 0xc0006daf30, 0xc000593a40, 0x41, 0x41, 0x987ab3ff9c0b346e, 0x2c0a78bbe644a59c, 0x763837b33f1d9078, ...)
	/go/src/github.com/filecoin-project/go-filecoin/mining/block_generate.go:51 +0x25b
github.com/filecoin-project/go-filecoin/mining.(*DefaultWorker).Mine(0xc000c56540, 0x16424a0, 0xc000dd4180, 0xc0006daf30, 0x0, 0xc000a979e0, 0x164dd00)
	/go/src/github.com/filecoin-project/go-filecoin/mining/worker.go:235 +0xb21
github.com/filecoin-project/go-filecoin/mining.(*timingScheduler).Start.func1(0xc0008d4770, 0x16423e0, 0xc000ee20c0, 0xc000ef8120, 0xc000a979e0)
	/go/src/github.com/filecoin-project/go-filecoin/mining/scheduler.go:127 +0x171
created by github.com/filecoin-project/go-filecoin/mining.(*timingScheduler).Start
	/go/src/github.com/filecoin-project/go-filecoin/mining/scheduler.go:97 +0x11b
FAIL	github.com/filecoin-project/go-filecoin/protocol/retrieval	0.288s
```

**Comment by laser** [comment]
I haven't seen this test fail in two weeks. I'm closing this issue.
