### ISSUE TITLE
[bug]go-filecoin panic and exit after runing about 24 hours

### ISSUE THREAD

**Issue by yaohcn** [filecoin-project/go-filecoin#2485]
**Describe the bug**
go-filecoin panic and exit after runing about 24 hours

**Screenshots**

> fatal error: concurrent map iteration and map write
goroutine 5988 [running]:
runtime.throw(0x1573205, 0x26)
    /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc089c87c68 sp=0xc089c87c38 pc=0x4dff82
runtime.mapiternext(0xc089c87d48)
    /usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc089c87cf0 sp=0xc089c87c68 pc=0x4c1777
github.com/filecoin-project/go-filecoin/core.(*MessagePool).timeoutMessages(0xc0000c39b0, 0x17c5260, 0xc032bc00c0,                0x7f3acef8d020, 0xc0000a8540, 0xc0a3da7770, 0x40, 0x80)
    /go/src/github.com/filecoin-project/go-filecoin/core/message_pool.go:185 +0x203 fp=0xc089c87db8 sp=0xc089c87cf0 pc=0xbb8183
github.com/filecoin-project/go-filecoin/core.(*MessagePool).UpdateMessagePool(0xc0000c39b0, 0x17c5260, 0xc032bc00c0,              0x7f3acef8d020, 0xc0000a8540, 0xc071d1b920, 0xc0a3da7770, 0x0, 0x0)
    /go/src/github.com/filecoin-project/go-filecoin/core/message_pool.go:155 +0x465 fp=0xc089c87ec8 sp=0xc089c87db8 pc=0xbb7f25
github.com/filecoin-project/go-filecoin/node.(*Node).handleNewHeaviestTipSet(0xc00000c1e0, 0x17c5260, 0xc032bc00c0, 0xc071d1b920, 0xc025015590)
    /go/src/github.com/filecoin-project/go-filecoin/node/node.go:660 +0x346 fp=0xc089c87fb8 sp=0xc089c87ec8 pc=0xcc8286
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc089c87fc0 sp=0xc089c87fb8 pc=0x50f521
created by github.com/filecoin-project/go-filecoin/node.(*Node).Start
    /go/src/github.com/filecoin-project/go-filecoin/node/node.go:543 +0x7f1

**Desktop (please complete the following information):**
 - OS: [ubuntu16.04]
 - Version [User Devnet Release 0.1.4]

**Comment by yaohcn** [comment]
fixed  by  #2522 . closed.
