### ISSUE TITLE
[bug] v0.0.4 of dht code can panic go-filecoin should update to more recent version

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2752]
**Describe the bug**
go-filecoin node panicked:
```
panic: counter already signaled done. use a new counter.

goroutine 38178114 [running]:
github.com/ipfs/go-todocounter.(*todoCounter).Increment(0xc0a7475ce0, 0xc000000001)
        /home/frrist/pkg/mod/github.com/ipfs/go-todocounter@v0.0.1/counter.go:86 +0xaf
github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).addPeerToQuery(0xc08e864e70, 0xc0231dcc00, 0x22)
        /home/frrist/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.4/query.go:200 +0x103
github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).Run(0xc08e864e70, 0x19402c0, 0xc0957503c0, 0xc0a7475590, 0x3, 0x3, 0x0, 0x0, 0x0)
        /home/frrist/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.4/query.go:136 +0x140
github.com/libp2p/go-libp2p-kad-dht.(*dhtQuery).Run(0xc0a7475620, 0x19402c0, 0xc0957503c0, 0xc0a7475590, 0x3, 0x3, 0x0, 0x0, 0x0)
        /home/frrist/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.4/query.go:70 +0xff
github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).GetClosestPeers.func2(0xc077359380, 0xc093c37c20, 0xc0a7475620, 0x1940340, 0xc077359320, 0xc0a7475590, 0x3, 0x3, 0xc08dc42900, 0x26)
        /home/frrist/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.4/lookup.go:96 +0xdb
created by github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).GetClosestPeers
        /home/frrist/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.4/lookup.go:92 +0x358
```
**To Reproduce**
Happens non-deterministically, running node for sometime should surface panic. 

**Expected behavior**
Node does not panic. 

**Diagnostic information**

- Filecoin Inspect Output:
```
  "Disk": {
    "FSType": "61267",
    "Free": 412155428864,
    "Total": 387160211456
  },
  "Environment": {
    "FIL_API": "",
    "FIL_PATH": "/home/frrist/filecoin0",
    "GOPATH": "/home/frrist"
  },
  "FilecoinVersion": "d7c3b1df109b7d3e119302a02ba956ab75fa2bb2",
  "Memory": {
    "Swap": 0,
    "Virtual": 13021308000
  },
  "Runtime": {
    "Arch": "amd64",
    "Compiler": "gc",
    "GoMaxProcs": 8,
    "NumCGoCalls": 767,
    "NumGoRoutines": 547,
    "NumProc": 8,
    "OS": "linux",
    "Version": "go1.12.1"
  }
}
```
- Current Head: `zDPWYqFD5cJX3tbcxDw7dkc4ZkxRexN7Gc8oCRCdfArj7tLWC1bG`

**Additional context**
The panic in the dht was addressed here: https://github.com/libp2p/go-libp2p-kad-dht/issues/292
go-filecoin should use a version of dht with said fix.

**Comment by frrist** [comment]
dup of #2753.
