### ISSUE TITLE
[bug]User devnet 0.2.1 crashed for 10 mins

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/go-filecoin#2756]
well, i update the `go-filecoin` to v0.2.1 , and reinitialize my node.
But it crashed about 10 mins later.

Here is the crash log, and it occured several times. The reasons are similar.

```
^[[0;37m10:26:32.595 ^[[31mERROR ^[[0;34m      node: ^[[0mprocessMessage(): validation error adding message to pool: message nonce (62147) is too much greater than actor nonce (0) ^[[0;37mnode.go:1040^[[0m
^[[0;37m10:26:32.631 ^[[31mERROR ^[[0;34m      node: ^[[0mprocessMessage(): validation error adding message to pool: message nonce (62148) is too much greater than actor nonce (0) ^[[0;37mnode.go:1040^[[0m
^[[0;37m10:26:32.675 ^[[31mERROR ^[[0;34m      node: ^[[0mprocessMessage(): validation error adding message to pool: message nonce (62149) is too much greater than actor nonce (0) ^[[0;37mnode.go:1040^[[0m
^[[0;37m10:26:32.720 ^[[31mERROR ^[[0;34m      node: ^[[0mprocessMessage(): validation error adding message to pool: message nonce (62150) is too much greater than actor nonce (0) ^[[0;37mnode.go:1040^[[0m
^[[0;37m10:26:32.723 ^[[31mERROR ^[[0;34m      node: ^[[0mprocessMessage(): validation error adding message to pool: message nonce (62151) is too much greater than actor nonce (0) ^[[0;37mnode.go:1040^[[0m
^[[0;37m10:26:32.750 ^[[31mERROR ^[[0;34m      node: ^[[0mprocessMessage(): validation error adding message to pool: message nonce (62152) is too much greater than actor nonce (0) ^[[0;37mnode.go:1040^[[0m
panic: counter already signaled done. use a new counter.

goroutine 2747370 [running]:
github.com/ipfs/go-todocounter.(*todoCounter).Increment(0xc053e95e30, 0xc000000001)
        /go/pkg/mod/github.com/ipfs/go-todocounter@v0.0.1/counter.go:86 +0xaf
github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).addPeerToQuery(0xc0562ddb80, 0xc0024c0990, 0x22)
        /go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.4/query.go:200 +0x103
github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).Run(0xc0562ddb80, 0x1ac3c00, 0xc053e96b00, 0xc053e95a10, 0x3, 0x3, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.4/query.go:136 +0x140
github.com/libp2p/go-libp2p-kad-dht.(*dhtQuery).Run(0xc053e95a70, 0x1ac3c00, 0xc053e96b00, 0xc053e95a10, 0x3, 0x3, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.4/query.go:70 +0xff
github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).GetClosestPeers.func2(0xc05bdc6ea0, 0xc0538273c0, 0xc053e95a70, 0x1ac3c80, 0xc05bdc6de0, 0xc053e95a10, 0x3, 0x3, 0xc01a1bf3b0, 0x26)
        /go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.4/lookup.go:96 +0xdb
created by github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).GetClosestPeers
        /go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.4/lookup.go:92 +0x358
```

**Comment by anorth** [comment]
This looks like the same issue as #2753, thanks.
