### ISSUE TITLE
[bug] Node panic while initializing sector builder

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#3129]
This is occurring during the deployment of the nightly devnet. The first failure occurred during a call to `mining start`. Getting the entire original stack trace in the correct order is a little difficult but I was able to get soem of the trace points.
```
github.com/ipfs/go-ipfs-cmds.(*Command).Call(0x278b060, 0xc0001ce930, 0x1aa1d80, 0xc009632500, 0x1a87080, 0xc0095c4e80)
github.com/ipfs/go-ipfs-cmds/http.(*handler).ServeHTTP(0xc00000f9e0, 0x1a9e0c0, 0xc0098740e0, 0xc00986c300)
github.com/filecoin-project/go-filecoin/node.(*Node).StartMining-fm(0x1aa1880, 0xc009601c20, 0x3, 0x0)
github.com/filecoin-project/go-filecoin/node.initSectorBuilderForNode(0x1aa1880, 0xc009601c20, 0xc00000c1e0, 0xc00000c2b8, 0x19832f0, 0xc00000c2b8, 0xc00000c2b8)
github.com/filecoin-project/go-filecoin/proofs/sectorbuilder.NewRustSectorBuilder(0x1aabca0, 0xc0003e17d0, 0x1, 0xc009933830, 0x23, 0xc0096de9e0, 0x15, 0xc009933860, 0x22, 0xc009933830, ...)
```

The below stack trace is from when the node restarted.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffffffffff pc=0xffffffffffffffff]

runtime stack:
runtime.throw(0x183bbbe, 0x2a)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0xda3c90, 0xc00935f428, 0x5053ef)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc00935f3e0 sp=0xc00935f3a8 pc=0x4dbeab
github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder._Cfunc_sector_builder_ffi_init_sector_builder(0x10000000, 0x102, 0x1, 0x7f627c000ef0, 0x7f627c000f20, 0x7f627c000f80, 0x7f627c000f50, 0x1, 0x0)
        _cgo_gotypes.go:527 +0x51 fp=0xc00935f428 sp=0xc00935f3e0 pc=0x9911c1
github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder.InitSectorBuilder(0x10000000, 0x102, 0x1, 0xc00978c660, 0x23, 0x411ee197baf61352, 0x4281d36ce9e0d913, 0x998d88cd, 0x0, 0xc00978c690, ...)
        /go/src/github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder/cgo_bindings.go:210 +0x22a fp=0xc00935f4c8 sp=0xc00935f428 pc=0x9927ba
github.com/filecoin-project/go-filecoin/proofs/sectorbuilder.NewRustSectorBuilder(0x1aabca0, 0xc0093bb6b0, 0x1, 0xc00978c660, 0x23, 0xc0000bdbc0, 0x15, 0xc00978c690, 0x22, 0xc00978c660, ...)
        /go/src/github.com/filecoin-project/go-filecoin/proofs/sectorbuilder/rustsectorbuilder.go:60 +0x140 fp=0xc00935f5c8 sp=0xc00935f4c8 pc=0x9a10c0
github.com/filecoin-project/go-filecoin/node.initSectorBuilderForNode(0x1aa17c0, 0xc0003ec1c0, 0xc00000c1e0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/filecoin-project/go-filecoin/node/node.go:930 +0x52f fp=0xc00935f760 sp=0xc00935f5c8 pc=0xd6291f
github.com/filecoin-project/go-filecoin/node.(*Node).setupMining(0xc00000c1e0, 0x1aa17c0, 0xc0003ec1c0, 0x0, 0x0)
        /go/src/github.com/filecoin-project/go-filecoin/node/node.go:606 +0x43 fp=0xc00935f7a8 sp=0xc00935f760 pc=0xd60583
github.com/filecoin-project/go-filecoin/node.(*Node).Start(0xc00000c1e0, 0x1aa17c0, 0xc0003ec1c0, 0x4, 0xc00935f9a8)
        /go/src/github.com/filecoin-project/go-filecoin/node/node.go:511 +0xbf5 fp=0xc00935f948 sp=0xc00935f7a8 pc=0xd5fec5
github.com/filecoin-project/go-filecoin/commands.runAPIAndWait(0x1aa17c0, 0xc0003ec1c0, 0xc00000c1e0, 0xc0000c1a40, 0xc00030b030, 0x0, 0x0)
        /go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:131 +0x68 fp=0xc00935fa58 sp=0xc00935f948 pc=0xd77078
github.com/filecoin-project/go-filecoin/commands.daemonRun(0xc00030b030, 0x1aa1d00, 0xc0000c1860, 0x1a87080, 0xc0003ec200, 0x16ed3a0, 0xc0000c1918)
        /go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:118 +0x7bc fp=0xc00935fba0 sp=0xc00935fa58 pc=0xd7697c
github.com/filecoin-project/go-filecoin/commands.glob..func37(0xc00030b030, 0x1aa1d00, 0xc0000c1860, 0x1a87080, 0xc0003ec200, 0x1a884c0, 0x278bd00)
        /go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:44 +0x53 fp=0xc00935fbe8 sp=0xc00935fba0 pc=0xd82cf3
github.com/ipfs/go-ipfs-cmds.(*executor).Execute(0xc0000be6b0, 0xc00030b030, 0x1aa1d00, 0xc0000c1860, 0x1a87080, 0xc0003ec200, 0xc0002e9d18, 0x4e2c15)
        /go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/executor.go:81 +0x171 fp=0xc00935fcb8 sp=0xc00935fbe8 pc=0x9e5cb1
github.com/filecoin-project/go-filecoin/commands.(*executor).Execute(0xc000371080, 0xc00030b030, 0x1aa1d00, 0xc0000c1860, 0x1a87080, 0xc0003ec200, 0xc0000c1860, 0x0)
        /go/src/github.com/filecoin-project/go-filecoin/commands/main.go:223 +0x3a2 fp=0xc00935fd28 sp=0xc00935fcb8 pc=0xd7b5b2
github.com/ipfs/go-ipfs-cmds/cli.Run(0x1aa1800, 0xc0000ba010, 0x269f300, 0xc0000c4000, 0x7, 0x7, 0xc0000be000, 0xc0000be008, 0xc0000be010, 0x19804d8, ...)
        /go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/cli/run.go:138 +0xa63 fp=0xc00935feb8 sp=0xc00935fd28 pc=0xd74213
github.com/filecoin-project/go-filecoin/commands.Run(0xc0000c4000, 0x7, 0x7, 0xc0000be000, 0xc0000be008, 0xc0000be010, 0x0, 0x0, 0xda0d37)
        /go/src/github.com/filecoin-project/go-filecoin/commands/main.go:202 +0xad fp=0xc00935ff30 sp=0xc00935feb8 pc=0xd7b0dd
main.main()
        /go/src/github.com/filecoin-project/go-filecoin/main.go:46 +0x2ff fp=0xc00935ff98 sp=0xc00935ff30 pc=0xda376f
runtime.main()
        /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc00935ffe0 sp=0xc00935ff98 pc=0x507fdc
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00935ffe8 sp=0xc00935ffe0 pc=0x535dd1
```

**Additional Information**

This is from the 33ffd9 nightly build.

**Comment by travisperson** [comment]
I ran the deployment again and was not able to repro. I also ran through the same commands locally and did not get a repro.

Might be worth looking into just to see if something pops out, but I've removed the P1.

**Comment by travisperson** [comment]
Hit it again on nightly-23991-a1771a

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffffffffff pc=0xffffffffffffffff]

runtime stack:
runtime.throw(0x1869167, 0x2a)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0xdc7f90, 0xc0001e1428, 0x50556f)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0001e13e0 sp=0xc0001e13a8 pc=0x4dbeab
github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder._Cfunc_sector_builder_ffi_init_sector_builder(0x10000000, 0x102, 0x1, 0x7f5eac000b20, 0x7f5eac000b50, 0x7f5eac000bb0, 0x7f5eac000b80, 0x1, 0x0)
	_cgo_gotypes.go:527 +0x51 fp=0xc0001e1428 sp=0xc0001e13e0 pc=0x99cb31
github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder.InitSectorBuilder(0x10000000, 0x102, 0x1, 0xc0099c84e0, 0x23, 0xcd69cb098a783030, 0xaeeabc889a9cd38a, 0x9d42cf1c, 0x0, 0xc0099c8510, ...)
	/go/src/github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder/cgo_bindings.go:210 +0x22a fp=0xc0001e14c8 sp=0xc0001e1428 pc=0x99e12a
github.com/filecoin-project/go-filecoin/proofs/sectorbuilder.NewRustSectorBuilder(0x1ade6c0, 0xc0098e5a10, 0x1, 0xc0099c84e0, 0x23, 0xc0002eb5a0, 0x15, 0xc0099c8510, 0x22, 0xc0099c84e0, ...)
	/go/src/github.com/filecoin-project/go-filecoin/proofs/sectorbuilder/rustsectorbuilder.go:60 +0x140 fp=0xc0001e15c8 sp=0xc0001e14c8 pc=0x9aca30
github.com/filecoin-project/go-filecoin/node.initSectorBuilderForNode(0x1ad3ec0, 0xc0003c7cc0, 0xc00000c1e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/filecoin-project/go-filecoin/node/node.go:932 +0x52f fp=0xc0001e1760 sp=0xc0001e15c8 pc=0xd86ccf
github.com/filecoin-project/go-filecoin/node.(*Node).setupMining(0xc00000c1e0, 0x1ad3ec0, 0xc0003c7cc0, 0x0, 0x0)
	/go/src/github.com/filecoin-project/go-filecoin/node/node.go:608 +0x43 fp=0xc0001e17a8 sp=0xc0001e1760 pc=0xd84933
github.com/filecoin-project/go-filecoin/node.(*Node).Start(0xc00000c1e0, 0x1ad3ec0, 0xc0003c7cc0, 0x4, 0xc0001e19a8)
	/go/src/github.com/filecoin-project/go-filecoin/node/node.go:513 +0xbf5 fp=0xc0001e1948 sp=0xc0001e17a8 pc=0xd84275
github.com/filecoin-project/go-filecoin/commands.runAPIAndWait(0x1ad3ec0, 0xc0003c7cc0, 0xc00000c1e0, 0xc0002f7020, 0xc000380d20, 0x0, 0x0)
	/go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:131 +0x68 fp=0xc0001e1a58 sp=0xc0001e1948 pc=0xd9b218
github.com/filecoin-project/go-filecoin/commands.daemonRun(0xc000380d20, 0x1ad4400, 0xc0002f6e40, 0x1ab8fc0, 0xc0003c7d00, 0x17167c0, 0xc0002f6ef8)
	/go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:118 +0x7bc fp=0xc0001e1ba0 sp=0xc0001e1a58 pc=0xd9ab1c
github.com/filecoin-project/go-filecoin/commands.glob..func37(0xc000380d20, 0x1ad4400, 0xc0002f6e40, 0x1ab8fc0, 0xc0003c7d00, 0x1aba480, 0x27da340)
	/go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:44 +0x53 fp=0xc0001e1be8 sp=0xc0001e1ba0 pc=0xda6fb3
github.com/ipfs/go-ipfs-cmds.(*executor).Execute(0xc0002e8508, 0xc000380d20, 0x1ad4400, 0xc0002f6e40, 0x1ab8fc0, 0xc0003c7d00, 0xc00029bd18, 0x4e2c15)
	/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/executor.go:81 +0x171 fp=0xc0001e1cb8 sp=0xc0001e1be8 pc=0x9f1621
github.com/filecoin-project/go-filecoin/commands.(*executor).Execute(0xc0003c87a0, 0xc000380d20, 0x1ad4400, 0xc0002f6e40, 0x1ab8fc0, 0xc0003c7d00, 0xc0002f6e40, 0x0)
	/go/src/github.com/filecoin-project/go-filecoin/commands/main.go:223 +0x3a2 fp=0xc0001e1d28 sp=0xc0001e1cb8 pc=0xd9f872
github.com/ipfs/go-ipfs-cmds/cli.Run(0x1ad3f00, 0xc000038018, 0x26ee780, 0xc000032070, 0x7, 0x7, 0xc000010010, 0xc000010018, 0xc000010020, 0x19ada08, ...)
	/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/cli/run.go:138 +0xa63 fp=0xc0001e1eb8 sp=0xc0001e1d28 pc=0xd983b3
github.com/filecoin-project/go-filecoin/commands.Run(0xc000032070, 0x7, 0x7, 0xc000010010, 0xc000010018, 0xc000010020, 0x0, 0x0, 0xdc5042)
	/go/src/github.com/filecoin-project/go-filecoin/commands/main.go:202 +0xad fp=0xc0001e1f30 sp=0xc0001e1eb8 pc=0xd9f39d
main.main()
	/go/src/github.com/filecoin-project/go-filecoin/main.go:46 +0x2ff fp=0xc0001e1f98 sp=0xc0001e1f30 pc=0xdc7a6f
runtime.main()
	/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc0001e1fe0 sp=0xc0001e1f98 pc=0x50815c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0001e1fe8 sp=0xc0001e1fe0 pc=0x535f51
```

**Comment by laser** [comment]
Looking at the stack trace, it appears to be the case that this node was using 256MiB sectors (first argument to the initializer, `0x10000000`):

> github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder._Cfunc_sector_builder_ffi_init_sector_builder(0x10000000, 0x102, 0x1, 0x7f5eac000b20, 0x7f5eac000b50, 0x7f5eac000bb0, 0x7f5eac000b80, 0x1, 0x0)

@travisperson - Would you mind confirming that the environment in which the stack trace is observed is configured such that the node uses 256MiB sectors?

**Comment by travisperson** [comment]
@laser yes, nightly is suppose to be using 256MiB sectors

**Comment by travisperson** [comment]
I think this has gone away. I haven't seen it in a while so I'm going to close this issue for now.

**Comment by laser** [comment]
That's excellent news, @travisperson. Thank you!

**Comment by travisperson** [comment]
Ran into this again, deploying the nightly to see if it reproduces. 

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffffffffff pc=0xffffffffffffffff]

runtime stack:
runtime.throw(0x186c29b, 0x2a)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0xdc8460, 0xc009373460, 0x504f2f)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc009373418 sp=0xc0093733e0 pc=0x4db86b
github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder._Cfunc_sector_builder_ffi_init_sector_builder(0x10000000, 0x102, 0x1, 0x7f7acc000c50, 0x7f7acc000c80, 0x7f7acc000ce0, 0x7f7acc000cb0, 0x1, 0x0)
	_cgo_gotypes.go:527 +0x51 fp=0xc009373460 sp=0xc009373418 pc=0x99c4f1
github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder.InitSectorBuilder(0x10000000, 0x102, 0x1, 0xc009892e70, 0x23, 0x2571f4fb92ed3c17, 0xd1a2ded6d3b49a1c, 0xd58d5d7c, 0x0, 0xc009892ea0, ...)
	/go/src/github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder/cgo_bindings.go:210 +0x22a fp=0xc009373500 sp=0xc009373460 pc=0x99daea
github.com/filecoin-project/go-filecoin/proofs/sectorbuilder.NewRustSectorBuilder(0x1ae19c0, 0xc00979ba10, 0x1, 0xc009892e70, 0x23, 0xc0000bdc60, 0x15, 0xc009892ea0, 0x22, 0xc009892e70, ...)
	/go/src/github.com/filecoin-project/go-filecoin/proofs/sectorbuilder/rustsectorbuilder.go:60 +0x140 fp=0xc009373600 sp=0xc009373500 pc=0x9ac3f0
github.com/filecoin-project/go-filecoin/node.initSectorBuilderForNode(0x1ad71c0, 0xc0003ce980, 0xc0003561c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/filecoin-project/go-filecoin/node/node.go:970 +0x52f fp=0xc009373798 sp=0xc009373600 pc=0xd86c2f
github.com/filecoin-project/go-filecoin/node.(*Node).setupMining(0xc0003561c0, 0x1ad71c0, 0xc0003ce980, 0x0, 0x0)
	/go/src/github.com/filecoin-project/go-filecoin/node/node.go:640 +0x43 fp=0xc0093737e0 sp=0xc009373798 pc=0xd84593
github.com/filecoin-project/go-filecoin/node.(*Node).Start(0xc0003561c0, 0x1ad71c0, 0xc0003ce980, 0x4, 0xc0093739a8)
	/go/src/github.com/filecoin-project/go-filecoin/node/node.go:511 +0x9d2 fp=0xc009373948 sp=0xc0093737e0 pc=0xd83cf2
github.com/filecoin-project/go-filecoin/commands.runAPIAndWait(0x1ad71c0, 0xc0003ce980, 0xc0003561c0, 0xc0000c1920, 0xc0002f0ee0, 0x0, 0x0)
	/go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:131 +0x68 fp=0xc009373a58 sp=0xc009373948 pc=0xd9b6e8
github.com/filecoin-project/go-filecoin/commands.daemonRun(0xc0002f0ee0, 0x1ad7700, 0xc0000c1740, 0x1abc2c0, 0xc0003ce9c0, 0x17194c0, 0xc0000c17f8)
	/go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:118 +0x7bc fp=0xc009373ba0 sp=0xc009373a58 pc=0xd9afec
github.com/filecoin-project/go-filecoin/commands.glob..func37(0xc0002f0ee0, 0x1ad7700, 0xc0000c1740, 0x1abc2c0, 0xc0003ce9c0, 0x1abd780, 0x27de380)
	/go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:44 +0x53 fp=0xc009373be8 sp=0xc009373ba0 pc=0xda7483
github.com/ipfs/go-ipfs-cmds.(*executor).Execute(0xc0000be730, 0xc0002f0ee0, 0x1ad7700, 0xc0000c1740, 0x1abc2c0, 0xc0003ce9c0, 0xc0002bbd18, 0x4e25d5)
	/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/executor.go:81 +0x171 fp=0xc009373cb8 sp=0xc009373be8 pc=0x9f0fe1
github.com/filecoin-project/go-filecoin/commands.(*executor).Execute(0xc000337e60, 0xc0002f0ee0, 0x1ad7700, 0xc0000c1740, 0x1abc2c0, 0xc0003ce9c0, 0xc0000c1740, 0x0)
	/go/src/github.com/filecoin-project/go-filecoin/commands/main.go:223 +0x3a2 fp=0xc009373d28 sp=0xc009373cb8 pc=0xd9fd42
github.com/ipfs/go-ipfs-cmds/cli.Run(0x1ad7200, 0xc0000ba010, 0x26f2780, 0xc0000c4000, 0x7, 0x7, 0xc0000be000, 0xc0000be008, 0xc0000be010, 0x19b0b40, ...)
	/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/cli/run.go:138 +0xa63 fp=0xc009373eb8 sp=0xc009373d28 pc=0xd98883
github.com/filecoin-project/go-filecoin/commands.Run(0xc0000c4000, 0x7, 0x7, 0xc0000be000, 0xc0000be008, 0xc0000be010, 0x0, 0x0, 0xdc5512)
	/go/src/github.com/filecoin-project/go-filecoin/commands/main.go:202 +0xad fp=0xc009373f30 sp=0xc009373eb8 pc=0xd9f86d
main.main()
	/go/src/github.com/filecoin-project/go-filecoin/main.go:46 +0x2ff fp=0xc009373f98 sp=0xc009373f30 pc=0xdc7f3f
runtime.main()
	/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc009373fe0 sp=0xc009373f98 pc=0x507b1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc009373fe8 sp=0xc009373fe0 pc=0x535911
```

**Comment by travisperson** [comment]
I'm now consistently running into this. So far I've hit three times in a row. On the last one I trailed the logs so I could capture the first failure during setup.

I'm going to now run this locally to see if I can see the same issue to try and determine if it's due to our deployment with docker, or some issue with the code at the moment.

```
{"timestamp":"2019-08-01T17:32:36.26593667Z","level":"DEBUG","system":"cmds/http","message":"incoming API request:  /config?arg=mining.minerAddress\u0026arg=t2c46o3ex36ryskhe2wtj5nxvc2f6f3do
vdh7q3fi\u0026encoding=json\u0026repodir=%2Fvar%2Flocal%2Ffilecoin%2Frepo\u0026stream-channels=true","file":"handler.go:90"}
{"timestamp":"2019-08-01T17:32:36.509896377Z","level":"DEBUG","system":"cmds/http","message":"incoming API request:  /wallet/import?encoding=json\u0026repodir=%2Fvar%2Flocal%2Ffilecoin%2Frep
o\u0026stream-channels=true","file":"handler.go:90"}
{"timestamp":"2019-08-01T17:32:36.746049514Z","level":"DEBUG","system":"cmds/http","message":"incoming API request:  /config?arg=wallet.defaultAddress\u0026arg=t15tyzro7dhukp2f7j7gd4i73il2xg
qjv6rqpjkgi\u0026encoding=json\u0026repodir=%2Fvar%2Flocal%2Ffilecoin%2Frepo\u0026stream-channels=true","file":"handler.go:90"}
{"timestamp":"2019-08-01T17:32:37.001656869Z","level":"DEBUG","system":"cmds/http","message":"incoming API request:  /id?encoding=json\u0026repodir=%2Fvar%2Flocal%2Ffilecoin%2Frepo\u0026stre
am-channels=true","file":"handler.go:90"}
{"timestamp":"2019-08-01T17:32:37.222571061Z","level":"DEBUG","system":"cmds/http","message":"incoming API request:  /miner/update-peerid?arg=t2c46o3ex36ryskhe2wtj5nxvc2f6f3dovdh7q3fi\u0026a
rg=Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4\u0026encoding=json\u0026from=t15tyzro7dhukp2f7j7gd4i73il2xgqjv6rqpjkgi\u0026gas-limit=300\u0026gas-price=0.000000001\u0026repodir=%2Fvar%2Fl
ocal%2Ffilecoin%2Frepo\u0026stream-channels=true","file":"handler.go:90"}
{"timestamp":"2019-08-01T17:32:37.223866797Z","level":"DEBUG","system":"node","message":"Received new message from network: SignedMessage cid=[bafy2bzacedlhvrbogbynjlvozs6ocyu3impcappmnygr3f
sddera7d2c4aya4]: {\n  \"meteredMessage\": {\n    \"message\": {\n      \"to\": \"t2c46o3ex36ryskhe2wtj5nxvc2f6f3dovdh7q3fi\",\n      \"from\": \"t15tyzro7dhukp2f7j7gd4i73il2xgqjv6rqpjkgi\",\n      \"nonce\": \"3\",\n      \"value\": \"0\",\n      \"method\": \"updatePeerID\",\n      \"params\": \"gVgiEiDbXbBmGs1XgNWvOhNU42yekJfMBSr7U4fZYPsDbHxqFQ==\"\n    },\n    \"gasPrice\": \"0.000000001\",\n    \"gasLimit\": \"300\"\n  },\n  \"signature\": \"eXtvF3mxe8KxebvdJ/DpiWKJFo7aLFue+ZaQOtEPkP96PuTTnNsuMof9zRu0L3p000I/l7OaSWs0pys14jcMtwE=\"\n}","file":"message.go:22"}
{"timestamp":"2019-08-01T17:32:37.458382175Z","level":"DEBUG","system":"cmds/http","message":"incoming API request:  /mining/start?encoding=json\u0026repodir=%2Fvar%2Flocal%2Ffilecoin%2Frepo\u0026stream-channels=true","file":"handler.go:90"}
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffffffffff pc=0xffffffffffffffff]

runtime stack:
runtime.throw(0x186c29b, 0x2a)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 372 [syscall]:
runtime.cgocall(0xdc8460, 0xc0098d3428, 0x504f2f)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0098d33e0 sp=0xc0098d33a8 pc=0x4db86b
github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder._Cfunc_sector_builder_ffi_init_sector_builder(0x10000000, 0x102, 0x1, 0x7f2d34000b20, 0x7f2d34000b50, 0x7f2d34000bb0, 0x7f2d34000b80, 0x1, 0x0)
        _cgo_gotypes.go:527 +0x51 fp=0xc0098d3428 sp=0xc0098d33e0 pc=0x99c4f1
github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder.InitSectorBuilder(0x10000000, 0x102, 0x1, 0xc0099679e0, 0x23, 0x2571f4fb92ed3c17, 0xd1a2ded6d3b49a1c, 0xd58d5d7c, 0x0, 0xc009967a10, ...)
        /go/src/github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder/cgo_bindings.go:210 +0x22a fp=0xc0098d34c8 sp=0xc0098d3428 pc=0x99daea
github.com/filecoin-project/go-filecoin/proofs/sectorbuilder.NewRustSectorBuilder(0x1ae19c0, 0xc0096379e0, 0x1, 0xc0099679e0, 0x23, 0xc000036c00, 0x15, 0xc009967a10, 0x22, 0xc0099679e0, ...)
        /go/src/github.com/filecoin-project/go-filecoin/proofs/sectorbuilder/rustsectorbuilder.go:60 +0x140 fp=0xc0098d35c8 sp=0xc0098d34c8 pc=0x9ac3f0
github.com/filecoin-project/go-filecoin/node.initSectorBuilderForNode(0x1ad7280, 0xc0099164b0, 0xc0003461c0, 0x15, 0xc0096aff40, 0x0, 0x0)
        /go/src/github.com/filecoin-project/go-filecoin/node/node.go:970 +0x52f fp=0xc0098d3760 sp=0xc0098d35c8 pc=0xd86c2f
github.com/filecoin-project/go-filecoin/node.(*Node).setupMining(0xc0003461c0, 0x1ad7280, 0xc0099164b0, 0xc000036c00, 0x15)
        /go/src/github.com/filecoin-project/go-filecoin/node/node.go:640 +0x43 fp=0xc0098d37a8 sp=0xc0098d3760 pc=0xd84593
github.com/filecoin-project/go-filecoin/node.(*Node).StartMining(0xc0003461c0, 0x1ad7280, 0xc0099164b0, 0x27dd6e0, 0xc009903fe0)
        /go/src/github.com/filecoin-project/go-filecoin/node/node.go:814 +0xa18 fp=0xc0098d38a8 sp=0xc0098d37a8 pc=0xd86618
github.com/filecoin-project/go-filecoin/node.(*Node).StartMining-fm(0x1ad7280, 0xc0099164b0, 0x3, 0x0)
        /go/src/github.com/filecoin-project/go-filecoin/node/node.go:799 +0x3e fp=0xc0098d38e0 sp=0xc0098d38a8 pc=0xd8b22e
github.com/filecoin-project/go-filecoin/protocol/block.(*MiningAPI).MiningStart(...)
        /go/src/github.com/filecoin-project/go-filecoin/protocol/block/mining_api.go:82
github.com/filecoin-project/go-filecoin/commands.glob..func93(0xc0002a6d90, 0x1ad7780, 0xc0096fcc00, 0x1abc2c0, 0xc0096c03c0, 0x0, 0x0)
        /go/src/github.com/filecoin-project/go-filecoin/commands/mining.go:49 +0x5e fp=0xc0098d3918 sp=0xc0098d38e0 pc=0xdb217e
github.com/ipfs/go-ipfs-cmds.(*Command).call(0x27dd6e0, 0xc0002a6d90, 0x1ad7780, 0xc0096fcc00, 0x1abc2c0, 0xc0096c03c0, 0x0, 0xc0097f79f0)
        /go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/command.go:107 +0x230 fp=0xc0098d3988 sp=0xc0098d3918 pc=0x9eee20
github.com/ipfs/go-ipfs-cmds.(*Command).Call(0x27dd6e0, 0xc0002a6d90, 0x1ad7780, 0xc0096fcc00, 0x1abc2c0, 0xc0096c03c0)
        /go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/command.go:77 +0x70 fp=0xc0098d3a00 sp=0xc0098d3988 pc=0x9ee9e0
github.com/ipfs/go-ipfs-cmds/http.(*handler).ServeHTTP(0xc0001f5420, 0x1ad3880, 0xc009860540, 0xc00970e600)
        /go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/http/handler.go:186 +0x992 fp=0xc0098d3b80 sp=0xc0098d3a00 pc=0xcb1392
github.com/ipfs/go-ipfs-cmds/http.prefixHandler.ServeHTTP(0x18409cd, 0x4, 0x1abcb80, 0xc0001f5420, 0x1ad3880, 0xc009860540, 0xc00970e600)
        /go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/http/apiprefix.go:24 +0xc3 fp=0xc0098d3bc8 sp=0xc0098d3b80 pc=0xcae143
github.com/ipfs/go-ipfs-cmds/http.(*prefixHandler).ServeHTTP(0xc0001f5440, 0x1ad3880, 0xc009860540, 0xc00970e600)
        <autogenerated>:1 +0x75 fp=0xc0098d3c10 sp=0xc0098d3bc8 pc=0xcb6eb5
github.com/rs/cors.(*Cors).Handler.func1(0x1ad3880, 0xc009860540, 0xc00970e600)
        /go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 +0x1af fp=0xc0098d3c68 sp=0xc0098d3c10 pc=0xcade3f
net/http.HandlerFunc.ServeHTTP(0xc0001f54e0, 0x1ad3880, 0xc009860540, 0xc00970e600)
        /usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc0098d3c90 sp=0xc0098d3c68 pc=0x7e8634
net/http.(*ServeMux).ServeHTTP(0xc0000ecfc0, 0x1ad3880, 0xc009860540, 0xc00970e600)
        /usr/local/go/src/net/http/server.go:2375 +0x1d6 fp=0xc0098d3cf0 sp=0xc0098d3c90 pc=0x7ea536
net/http.serverHandler.ServeHTTP(0xc0002d80d0, 0x1ad3880, 0xc009860540, 0xc00970e600)
        /usr/local/go/src/net/http/server.go:2774 +0xa8 fp=0xc0098d3d20 sp=0xc0098d3cf0 pc=0x7eb908
net/http.(*conn).serve(0xc0000c94a0, 0x1ad71c0, 0xc009908880)
        /usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc0098d3fc8 sp=0xc0098d3d20 pc=0x7e75f1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0098d3fd0 sp=0xc0098d3fc8 pc=0x535911
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4
```
