### ISSUE TITLE
Process exited with panic

### ISSUE THREAD

**Issue by ridewindx** [filecoin-project/go-filecoin#3391]
**Describe the bug**:
Press Ctrl + C to terminate go-filecoin process, but got:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc03721]
```

**Expected behavior**:
Exit without panic.

**Diagnostic information:**
```
goroutine 125 [running]:
github.com/ipfs/go-datastore/autobatch.(*Datastore).Flush(0xc0002f9860, 0x1, 0xc000374480)
	/root/go/pkg/mod/github.com/ipfs/go-datastore@v0.0.5/autobatch/autobatch.go:92 +0x211
github.com/libp2p/go-libp2p-kad-dht/providers.(*ProviderManager).run.func1(0xc000314280, 0xc015af5dc0, 0xc0002fc7c0)
	/root/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.1.1/providers/providers.go:214 +0x65
github.com/libp2p/go-libp2p-kad-dht/providers.(*ProviderManager).run(0xc0002fc7c0, 0x1aa8380, 0xc0000eb680)
	/root/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.1.1/providers/providers.go:297 +0xb01
github.com/jbenet/goprocess.(*process).Go.func1(0xc0001748b0, 0xc0000eb680, 0xc0000eb6e0)
	/root/go/pkg/mod/github.com/jbenet/goprocess@v0.1.3/impl-mutex.go:134 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
	/root/go/pkg/mod/github.com/jbenet/goprocess@v0.1.3/impl-mutex.go:133 +0x1f6
[root@tikv432002 filecoin]# go-filecoin daemon
```

- Filecoin Version: commit 72baa704781e3bd9c8635d928f331857cc683fba
- Filecoin Inspect Output:
- Initialization Command: go-filecoin daemon

**Comment by xueqingping** [comment]
the same as it,   and  memory is 8GB

**Comment by frrist** [comment]
Thanks @ridewindx. Going to close this as #946, #1124, and #2052 cover this behaviour. Will link to this in the aforementioned issues.
