### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [filecoin-project/go-filecoin#3661]
**Describe the bug**:
```
2019-11-18T02:08:42.174Z        INFO    chainsync.fetcher.graphsync     fetcher/graphsync_fetcher.go:158        fetching initial tipset { bafy2bzacebk4ckkdvzemxxd652y2gippnt2dzryrjsoypymahkbxdggrxmf6c } from peer QmQ9ZGEKZpGaFjPRhvPUkZAzPsV6dKhrPoYjdqzm6d3YYy
2019-11-18T02:08:42.175Z        INFO    chainsync.fetcher.graphsync     fetcher/graphsync_fetcher.go:158        fetching initial tipset { bafy2bzacebk4ckkdvzemxxd652y2gippnt2dzryrjsoypymahkbxdggrxmf6c } from peer Qmc5rknd4SWZyv3q3chekN3jxDpEEaddhujgbPfLUryGv9
2019-11-18T02:08:42.184Z        INFO    peer-tracker    discovery/peer_tracker.go:63    Track peer      {"chainInfo": "{source=QmQ9ZGEKZpGaFjPRhvPUkZAzPsV6dKhrPoYjdqzm6d3YYy sender:QmQ9ZGEKZpGaFjPRhvPUkZAzPsV6dKhrPoYjdqzm6d3YYy height=263 head={ bafy2bzacebk4ckkdvzemxxd652y2gippnt2dzryrjsoypymahkbxdggrxmf6c }}", "new": false, "count": 2, "trusted": false}
panic: runtime error: index out of range [0] with length 0

goroutine 20958 [running]:
github.com/filecoin-project/go-filecoin/internal/pkg/consensus.(*Expected).runMessages(0xc000434b00, 0x1b5c600, 0xc0195ece40, 0x1b5ec80, 0xc01f27dd90, 0x1b4d780, 0xc006674400, 0xc0257f12f0, 0x2, 0x2, ...)
        /root/go/src/github.com/filecoin-project/go-filecoin/internal/pkg/consensus/expected.go:303 +0xba2
github.com/filecoin-project/go-filecoin/internal/pkg/consensus.(*Expected).RunStateTransition(0xc000434b00, 0x1b5c600, 0xc01c12c210, 0xc0257f12f0, 0x2, 0x2, 0xc0333ba1e0, 0x2, 0x2, 0xc0195ec330, ...)
        /root/go/src/github.com/filecoin-project/go-filecoin/internal/pkg/consensus/expected.go:158 +0x5bc
github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/syncer.(*Syncer).syncOne(0xc000434c00, 0x1b5c600, 0xc01c12c210, 0xc014069f70, 0x1, 0x1, 0xc01b7809d0, 0x1, 0x1, 0xc014069f48, ...)
        /root/go/src/github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/syncer/syncer.go:248 +0xae4
github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/syncer.(*Syncer).HandleNewTipSet(0xc000434c00, 0x1b5c600, 0xc01c12c210, 0xc00e5f0ec0, 0x1, 0x0, 0x0)
        /root/go/src/github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/syncer/syncer.go:510 +0x105e
github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/dispatcher.(*Dispatcher).Start.func1(0x1b5c540, 0xc012edd800, 0xc0004ee780)
        /root/go/src/github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/dispatcher/dispatcher.go:138 +0x59a
created by github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/dispatcher.(*Dispatcher).Start
        /root/go/src/github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/dispatcher/dispatcher.go:96 +0x53
2019-11-18T02:08:42.533Z        INFO    badger  badger@v1.6.0/logger.go:46      All 1 tables opened in 1ms

2019-11-18T02:08:42.533Z        INFO    badger  badger@v1.6.0/logger.go:46      Replaying file id: 0 at offset: 4544

```
**Expected behavior**:
```
I ran the genesis node on local net, and it's also panic to restart at this point. 
And because it's a panic, so i just published this log to help developers who are familiar with this area judge whether it's a problem.
```
**Diagnostic information:**

- Filecoin Version: 

commit: 204837f72d20bd89889fcf92061c8846b238ccf4

- Filecoin Inspect Output: 

- Initialization Command:

**Comment by IPFS-grandhelmsman** [comment]
The code seems to be fixed in the latest commit.
