### ISSUE TITLE
Index out of range panic in drand chain sync

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#4129]
Observed early on in testnet-2

```
2020-05-15T08:12:08.213+1000	ERROR	chainsync.dispatcher	dispatcher/dispatcher.go:126	exiting
2020-05-15T08:12:08.213+1000	ERROR	chainsync.dispatcher	dispatcher/dispatcher.go:128	panic: runtime error: index out of range [0] with length 0
goroutine 272 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/dispatcher.(*Dispatcher).Start.func1.1()
	/Users/me/plabs/src/go-filecoin-1/internal/pkg/chainsync/internal/dispatcher/dispatcher.go:129 +0x100
panic(0x5d5e360, 0xc0758d85e0)
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:679 +0x1b2
github.com/filecoin-project/go-filecoin/internal/pkg/drand.(*GRPC).VerifyEntry(0xc000149180, 0xc075712660, 0xc0754b5d00, 0x1, 0x1, 0xc07b8a99c0)
	/Users/me/plabs/src/go-filecoin-1/internal/pkg/drand/drand_grpc.go:140 +0x127
github.com/filecoin-project/go-filecoin/internal/pkg/consensus.(*Expected).validateDRANDEntries(0xc0004cce70, 0x6193a40, 0xc07575ade0, 0xc000244500, 0x0, 0x0)
	/Users/me/plabs/src/go-filecoin-1/internal/pkg/consensus/expected.go:358 +0x6cb
github.com/filecoin-project/go-filecoin/internal/pkg/consensus.(*Expected).validateMining(0xc0004cce70, 0x6193a40, 0xc07575ade0, 0xc0753e4190, 0x1, 0x1, 0xc0001e3ed0, 0x1, 0x1, 0xc07ba86030, ...)
	/Users/me/plabs/src/go-filecoin-1/internal/pkg/consensus/expected.go:266 +0x6dd
github.com/filecoin-project/go-filecoin/internal/pkg/consensus.(*Expected).RunStateTransition(0xc0004cce70, 0x6193a40, 0xc075470930, 0xc0753e4190, 0x1, 0x1, 0xc0001e3ed0, 0x1, 0x1, 0xc075865620, ...)
	/Users/me/plabs/src/go-filecoin-1/internal/pkg/consensus/expected.go:154 +0x31e
github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/syncer.(*Syncer).syncOne(0xc0001fe270, 0x6193a40, 0xc075470930, 0xc0753e4178, 0x1, 0x1, 0xc0756d8d50, 0x1, 0x1, 0xc076cc8cd0, ...)
	/Users/me/plabs/src/go-filecoin-1/internal/pkg/chainsync/internal/syncer/syncer.go:286 +0x9c2
github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/syncer.(*Syncer).handleNewTipSet(0xc0001fe270, 0x6193a40, 0xc075470930, 0xc0755e42c0, 0x0, 0x0)
	/Users/me/plabs/src/go-filecoin-1/internal/pkg/chainsync/internal/syncer/syncer.go:543 +0xd24
github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/syncer.(*Syncer).HandleNewTipSet(0xc0001fe270, 0x6193980, 0xc075594280, 0xc0755e42c0, 0xc075433d00, 0x1, 0x1)
	/Users/me/plabs/src/go-filecoin-1/internal/pkg/chainsync/internal/syncer/syncer.go:454 +0x67
github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/dispatcher.(*Dispatcher).Start.func1(0x6193980, 0xc075594280, 0xc075570600)
	/Users/me/plabs/src/go-filecoin-1/internal/pkg/chainsync/internal/dispatcher/dispatcher.go:186 +0x411
created by github.com/filecoin-project/go-filecoin/internal/pkg/chainsync/internal/dispatcher.(*Dispatcher).Start
	/Users/me/plabs/src/go-filecoin-1/internal/pkg/chainsync/internal/dispatcher/dispatcher.go:124 +0x53
```

**Comment by anorth** [comment]
FIxed in #4130
